### ISSUE TITLE
Cache clearing won't work on load balanced environments

### ISSUE THREAD

**Issue by dawoe** [anthonydotnet/dangeasy-ucache#1]
Hi @anthonydotnet 

Haven't tried the package yet. But I can tell you that the cache clearing won't work on load balanced environments

The contentservice events are only fired on the server where the publish/delete actions take place. 

You will need to use the CacheRefreshers to make it work on all servers.

Dave

**Comment by anthonydotnet** [comment]
Hmm... which version of Umbraco?

Also, can you give me details of your hosting setup?

Anthony

**Comment by anthonydotnet** [comment]
Thanks for the feedback. I've fixed this now.

https://github.com/anthonydotnet/dangeasy-ucache/blob/master/src/DangEasy.UCache/Startup/UCacheStartup.cs

**Comment by dawoe** [comment]
NIce
